"""Two entry points to the same tasks is two chances to drift.

The README documents `make check` and `./make.ps1 check` as equivalent. Nobody notices when
they stop being equivalent, because each developer only ever runs one of them -- so it is
asserted here rather than trusted.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
MAKEFILE = ROOT / "Makefile"
SHIM = ROOT / "make.ps1"

# A documented Makefile target: `name: deps ## description`
MAKE_TARGET = re.compile(r"^([a-zA-Z][a-zA-Z0-9_-]*):.*?##\s*(.+)$", re.MULTILINE)
# A shim target: `'name' = @{ Help = '...'`
SHIM_TARGET = re.compile(
    r"^\s*'([a-zA-Z][a-zA-Z0-9_-]*)'\s*=\s*@\{\s*Help\s*=\s*'(.+?)'", re.MULTILINE
)

# `help` is generated by each runner in its own way and is not a shared task.
NOT_A_SHARED_TASK = frozenset({"help"})


@pytest.fixture(scope="module")
def make_targets() -> dict[str, str]:
    found = dict(MAKE_TARGET.findall(MAKEFILE.read_text(encoding="utf-8")))
    return {name: help_text.strip() for name, help_text in found.items()}


@pytest.fixture(scope="module")
def shim_targets() -> dict[str, str]:
    found = dict(SHIM_TARGET.findall(SHIM.read_text(encoding="utf-8")))
    return {name: help_text.strip() for name, help_text in found.items()}


def test_both_runners_exist() -> None:
    assert MAKEFILE.is_file()
    assert SHIM.is_file()


def test_the_two_runners_expose_the_same_targets(
    make_targets: dict[str, str], shim_targets: dict[str, str]
) -> None:
    documented = set(make_targets) - NOT_A_SHARED_TASK

    assert documented == set(shim_targets), (
        f"only in Makefile: {sorted(documented - set(shim_targets))}; "
        f"only in make.ps1: {sorted(set(shim_targets) - documented)}"
    )


def test_the_two_runners_describe_targets_identically(
    make_targets: dict[str, str], shim_targets: dict[str, str]
) -> None:
    """Divergent help text means one of them is describing behaviour it does not have."""
    mismatched = {
        name: (make_targets[name], shim_targets[name])
        for name in set(shim_targets) & set(make_targets)
        if make_targets[name] != shim_targets[name]
    }

    assert not mismatched, f"help text differs: {mismatched}"


def test_every_phony_target_is_documented(make_targets: dict[str, str]) -> None:
    """An undocumented target does not appear in `make help`, so nobody runs it."""
    phony = re.search(r"^\.PHONY:\s*(.+)$", MAKEFILE.read_text(encoding="utf-8"), re.MULTILINE)
    assert phony is not None
    declared = set(phony.group(1).split())

    assert declared == set(make_targets), (
        f"declared but undocumented: {sorted(declared - set(make_targets))}; "
        f"documented but not phony: {sorted(set(make_targets) - declared)}"
    )
